"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { onAuthStateChanged } from "firebase/auth"
import { collection, doc, getDoc, getDocs } from "firebase/firestore"
import { auth, db } from "@/app/lib/firebase"
import AppHeader from "@/app/components/AppHeader"
import LegalFooter from "@/app/components/LegalFooter"

type UserDoc={displayName?:string};type ResultDoc={correctCount?:number;totalQuestions?:number;accuracy?:number;createdAt?:any;updatedAt?:any}
const MENUS=[
{title:"学習",en:"Study",href:"/select-mode",desc:"日本語検定、介護用語、介護現場会話、介護福祉士試験対策をまとめて学習できます。",badge:"日本語 / 介護 / 資格",cls:"border-blue-200 bg-blue-50/50"},
{title:"AI",en:"AI Practice",href:"/select-mode#ai",desc:"AI会話とAIスピークで、職場・面接・日常会話の実践練習につなげます。",badge:"会話 + スピーク",cls:"border-purple-200 bg-purple-50/50"},
{title:"ゲーム",en:"Game",href:"/game",desc:"日本語バトルで語彙・文法・判断力をゲーム形式で反復できます。",badge:"日本語バトル",cls:"border-amber-200 bg-amber-50/60"},
]
function toDate(v:any){try{if(!v)return null;if(typeof v?.toDate==="function")return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?null:d}catch{return null}}
function fmt(d:Date|null){return d?d.toLocaleDateString("ja-JP"):"—"}
export default function HomePage(){const router=useRouter();const[loading,setLoading]=useState(true);const[userData,setUserData]=useState<UserDoc|null>(null);const[count,setCount]=useState(0);const[accuracy,setAccuracy]=useState(0);const[last,setLast]=useState<Date|null>(null);useEffect(()=>onAuthStateChanged(auth,async(user)=>{if(!user){router.replace("/login");return}try{const us=await getDoc(doc(db,"users",user.uid));if(us.exists())setUserData(us.data() as UserDoc);const rs=await getDocs(collection(db,"users",user.uid,"results"));const results=rs.docs.map(d=>d.data() as ResultDoc);setCount(results.length);let sum=0,n=0,tc=0,tq=0,l=0;for(const r of results){if(typeof r.accuracy==="number"){sum+=r.accuracy;n++}else if(typeof r.correctCount==="number"&&typeof r.totalQuestions==="number"&&r.totalQuestions>0){sum+=r.correctCount/r.totalQuestions*100;n++}if(typeof r.correctCount==="number")tc+=r.correctCount;if(typeof r.totalQuestions==="number")tq+=r.totalQuestions;const d=toDate(r.createdAt??r.updatedAt);if(d&&d.getTime()>l)l=d.getTime()}setAccuracy(n?Math.round(sum/n):tq?Math.round(tc/tq*100):0);setLast(l?new Date(l):null)}finally{setLoading(false)}}),[router]);if(loading)return <div className="app-shell"><AppHeader/><main className="page-shell"><div className="ui-card"><p className="text-sub">読み込み中...</p></div></main><LegalFooter/></div>;return <div className="app-shell"><AppHeader/><main className="page-shell"><section className="ui-card"><p className="eyebrow">PERSONAL HOME</p><h1 className="page-title">こんにちは {userData?.displayName||""}</h1><p className="page-lead">学習、AI練習、ゲームをこの3つに整理しました。迷わず次の学習に進めます。</p></section><section className="ui-card mt-5"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">LEARNING PROGRESS</p><h2 className="mt-2 card-title">学習状況</h2></div><span className="ui-badge">平均正答率 {accuracy}%</span></div><div className="mt-5 h-3 w-full overflow-hidden rounded-full bg-slate-200"><div className="h-3 rounded-full bg-blue-600" style={{width:`${Math.max(0,Math.min(accuracy,100))}%`}}/></div><div className="stat-grid mt-5"><Stat label="学習回数" value={`${count}回`}/><Stat label="正答率" value={`${accuracy}%`}/><Stat label="最終学習日" value={fmt(last)}/></div></section><section className="mt-6"><p className="eyebrow">MAIN MENU</p><h2 className="mt-2 card-title">始めるメニュー</h2><div className="grid-cards three mt-4">{MENUS.map(m=><Link key={m.href} href={m.href} className={`ui-card-link ${m.cls}`}><div className="ui-card-body"><span className="ui-badge">{m.en}</span><h3 className="mt-5 text-3xl font-black tracking-tight text-slate-900">{m.title}</h3><p className="mt-3 text-sm leading-7 text-slate-700">{m.desc}</p><div className="ui-card-actions"><span className="ui-btn ui-btn-primary">{m.badge} を開く</span></div></div></Link>)}</div></section></main><LegalFooter/></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="stat-card"><span className="stat-label">{label}</span><span className="stat-value">{value}</span></div>}
